v1_controllers:
    resource: '../src/Controller/Api'
    type: annotation
    prefix: 'v1'
ekreative_health_check:
    resource: '@EkreativeHealthCheckBundle/Resources/config/routes.xml'
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }