Knp\Component\Pager\Pagination\AbstractPagination:
  exclusion_policy: ALL
  accessor_order: custom
  custom_accessor_order: [currentPageNumber, items, pageCount, numItemsPerPage, totalCount]
  properties:
    items:
      expose: true
      access_type: public_method
      accessor:
        getter: getItems
      type: array
      serialized_name:
        data
    currentPageNumber:
      expose: true
      serialized_name:
        current_page
    numItemsPerPage:
      expose: true
      serialized_name:
        items_per_page
    totalCount:
      expose: true
      serialized_name:
        total_items
