Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination:
  exclusion_policy: ALL
  virtual_properties:
    getPageCount:
      expose: true
      serialized_name: page_count
      type: integer
      groups:
        - pagination